spring.application.name: myarmy
---
dashboard.url: http://127.0.0.1
---
fb:
  appSecret : c9455d3789ade975d13d3401dbe81161
  verifytoken: 267298547014539|YPhlWZTflmCH8nQt6eBMQnSQUv8
  accesstoken: EAAC76hJDh7YBAOyhW2rqkn9uhTCgZCWgFuFImmidWYy9OKDhqNIuSUrPqrMHUfYeuJZCRwYZAMBH1t0R7biVsGsuNo9ENiZB1xGYuYSWM6RzEAKXu2APMXP65o2mGBVxjW4qjFGdIjxodMWSlNlg1ZC7EZARDN5c4VmPy4CIlRgQZDZD
  serverURL : https://gomko.me/bot/api/v1/webhook
---
spring.jpa:
  database: MYSQL
  showSql: true
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  properties.hibernate.hbm2ddl.auto: update
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true

---
logging.level:
   org.springframework: INFO
   org.hibernate.SQL: DEBUG
   org.hibernate.type: TRACE
   org.hibernate.type.BasicTypeRegistry: WARN

##DataSource configuration
spring.datasource.url: jdbc:mysql://127.0.0.1/skhu-bot?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: skhu-bot
spring.datasource.password: 1234
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.initialize: true

---
#spring.datasource:
  #platform: h2
  #url: jdbc:h2:mem:skhu-bot;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
  #username: sa
  #initialize: true
---
spring.h2.console:
  enabled: true
  path : /h2-console
  settings.web-allow-others: true
